// The position in this list (starting at 1) is the room type id the backend
// stores, so the order must not change. New types go at the end.
export const ROOM_TYPES = [
  "Deluxe",
  "Super Deluxe",
  "Suite",
  "Premium",
  "Premiere Retreat",
  "Elite Suite",
  "Grand Deluxe",
  "Imperial Suite",
  "Supreme Retreat",
  "Royal Deluxe",
  "Prestige Suite",
  "Exclusive Retreat",
];

export const getRoomTypeId = (name) => ROOM_TYPES.indexOf(name) + 1;
export const getRoomTypeName = (id) =>
  ROOM_TYPES[Number(id) - 1] || `Room type ${id}`;

export const FACILITIES = [
  "Wi-Fi",
  "Air Conditioning",
  "Heater",
  "TV",
  "Refrigerator",
  "Microwave",
  "Coffee Maker",
  "Toaster",
  "Stove",
  "Oven",
  "Dishwasher",
  "Washer",
  "Dryer",
  "Hair Dryer",
  "Iron",
  "Towels",
  "Linens",
  "Toiletries",
  "Shampoo",
  "Conditioner",
  "Soap",
  "Toilet Paper",
  "Bathtub",
  "Shower",
  "Balcony",
  "Terrace",
  "Garden View",
  "Sea View",
  "Mountain View",
  "City View",
  "Lake View",
  "Private Entrance",
  "Elevator",
  "Parking",
  "Garage",
  "Fireplace",
  "Safety Box",
  "Smoke Detector",
  "Carbon Monoxide Detector",
  "First Aid Kit",
  "Fire Extinguisher",
  "Wheelchair Accessible",
  "Pet Friendly",
  "Swimming Pool",
  "Hot Tub",
  "Sauna",
  "Gym",
  "BBQ Grill",
  "Outdoor Furniture",
  "Outdoor Dining Area",
  "Playground",
  "Game Room",
  "Library",
  "Bicycle Rental",
  "Car Rental",
  "Airport Shuttle",
  "24-Hour Front Desk",
  "Concierge Service",
  "Daily Housekeeping",
  "Laundry Service",
  "Dry Cleaning",
  "Business Center",
  "Meeting Room",
  "Banquet Hall",
  "Restaurant",
  "Bar",
  "Café",
  "Room Service",
  "Mini Bar",
  "Breakfast Included",
  "All-Inclusive",
  "Family Friendly",
  "Kid-Friendly",
  "Adult Only",
  "Non-Smoking",
  "Smoking Area",
  "Eco-Friendly",
  "Solar Power",
  "Rainwater Harvesting",
  "Recycling",
  "Compost Bin",
  "Organic Garden",
  "Farm Stay",
  "Petting Zoo",
  "Horse Riding",
  "Fishing",
  "Hiking Trails",
  "Cycling Trails",
  "Ski-In/Ski-Out",
  "Beach Access",
  "Boat Rental",
  "Kayak Rental",
  "Surfboard Rental",
  "Scuba Diving",
  "Snorkeling",
  "Golf Course",
  "Tennis Court",
  "Basketball Court",
  "Volleyball Court",
  "Soccer Field",
  "Cricket Ground",
];

export const MAX_PACKAGE_IMAGES = 5;
