// export const facilitiesData = [
//   "Hairdryer",
//   "Shared_toilet",
//   "Sauna",
//   "Shower",
//   "Slippers",
//   "Toilet",
//   "Additional_bathroom",
//   "Toothbrush",
//   "Shampoo",
//   "Conditioner",
//   "Cd_player",
//   "Dvd_player",
//   "Fax",
//   "Radio",
//   "Satellitechannels",
//   "Telephone",
//   "Tv",
//   "Smartphone",
//   "Streamingservice_like_Netflix",
//   "Dining_table",
//   "Bottle_of_water",
//   "Chocolate_or_cookies",
//   "Fruits",
//   "Barbecue",
//   "Oven",
//   "Stovetop",
//   "Toaster",
//   "Dishwasher",
//   "Outdoor_furniture",
//   "Minibar",
//   "Kitchen",
//   "Key_card_access",
//   "Lockers",
//   "Key_access",
//   "Alarm_clock",
//   "Wake_up_service",
//   "Linen",
//   "Blanket",
//   "Extra_blankets",
//   "Pillow",
//   "Towels",
//   "Patio",
//   "City_view",
//   "Garden_view",
//   "Lake_view",
//   "Landmark_view",
//   "Mountain_view",
//   "Pool_view",
//   "River_view",
//   "Sea_view",
//   "Hearingaccessible",
//   "Adaptedbath",
//   "Raisedtoilet",
//   "Loweredsink",
//   "Showerchair",
//   "Entertainment_family_services",
//   "Baby_safety_gates",
//   "Books",
//   "DVDs",
//   "Smokealarm",
//   "Fire_extinguisher",
//   "Safety_features",
//   "Air_purifiers",
//   "Physicaldistancing",
//   "Handsanitiser",
// ];

export const roomTypes = [
  "Deluxe",
  "Super Deluxe",
  "Suite",
  "Premium",
  "Premiere Retreat",
  "Elite Suite",
  "Grand Deluxe",
  "Imperial Suite",
  "Supreme Retreat",
  "Royal Deluxe",
  "Prestige Suite",
  "Exclusive Retreat",
];

export const getRoomType = (roomType = "Deluxe") => {
  const roomTypeNumber = roomTypes.indexOf(roomType);
  return roomTypeNumber + 1;
}

export const facilitiesList = [
  "Wi-Fi",
  "Air Conditioning",
  "Heater",
  "TV",
  "Refrigerator",
  "Microwave",
  "Coffee Maker",
  "Toaster",
  "Stove",
  "Oven",
  "Dishwasher",
  "Washer",
  "Dryer",
  "Hair Dryer",
  "Iron",
  "Towels",
  "Linens",
  "Toiletries",
  "Shampoo",
  "Conditioner",
  "Soap",
  "Toilet Paper",
  "Bathtub",
  "Shower",
  "Balcony",
  "Terrace",
  "Garden View",
  "Sea View",
  "Mountain View",
  "City View",
  "Lake View",
  "Private Entrance",
  "Elevator",
  "Parking",
  "Garage",
  "Fireplace",
  "Safety Box",
  "Smoke Detector",
  "Carbon Monoxide Detector",
  "First Aid Kit",
  "Fire Extinguisher",
  "Wheelchair Accessible",
  "Pet Friendly",
  "Swimming Pool",
  "Hot Tub",
  "Sauna",
  "Gym",
  "BBQ Grill",
  "Outdoor Furniture",
  "Outdoor Dining Area",
  "Playground",
  "Game Room",
  "Library",
  "Bicycle Rental",
  "Car Rental",
  "Airport Shuttle",
  "24-Hour Front Desk",
  "Concierge Service",
  "Daily Housekeeping",
  "Laundry Service",
  "Dry Cleaning",
  "Business Center",
  "Meeting Room",
  "Banquet Hall",
  "Restaurant",
  "Bar",
  "Café",
  "Room Service",
  "Mini Bar",
  "Breakfast Included",
  "All-Inclusive",
  "Family Friendly",
  "Kid-Friendly",
  "Adult Only",
  "Non-Smoking",
  "Smoking Area",
  "Eco-Friendly",
  "Solar Power",
  "Rainwater Harvesting",
  "Recycling",
  "Compost Bin",
  "Organic Garden",
  "Farm Stay",
  "Petting Zoo",
  "Horse Riding",
  "Fishing",
  "Hiking Trails",
  "Cycling Trails",
  "Ski-In/Ski-Out",
  "Beach Access",
  "Boat Rental",
  "Kayak Rental",
  "Surfboard Rental",
  "Scuba Diving",
  "Snorkeling",
  "Golf Course",
  "Tennis Court",
  "Basketball Court",
  "Volleyball Court",
  "Soccer Field",
  "Cricket Ground",
];
